services:
  db:
    image: postgres:16-alpine
    container_name: FinFury-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: FinFury
    ports:
      - '5432:5432'
    volumes:
      - FinFury_pgdata:/var/lib/postgresql/data

volumes:
  FinFury_pgdata: